### ISSUE TITLE
ERROR: target server does not expose service "task"

### ISSUE THREAD

**Issue by remotejob** [sabouaram/dual-protocol-APIs#1]
grpcurl  -plaintext localhost:50051 list

grpc.reflection.v1.ServerReflection
grpc.reflection.v1alpha.ServerReflection
task.TaskService

grpcurl -plaintext -d '{"title": "gRPC Task", "description": "This is a test task."}' localhost:50051 task.TaskService

`Error invoking method "task.TaskService": target server does not expose service "task"`

protoc --version  

libprotoc 3.14.0

**Comment by remotejob** [comment]
It must be:
`grpcurl -import-path . -proto proto/task.proto -plaintext -d '{"title": "gRPC Task", "description": "This is a test task."}' localhost:50051 task.TaskService/CreateTask`

**Comment by sabouaram** [comment]
Hello Aleksander,

Thanks for the infos, I've seen that you closed this issue, if this is not completed, I can surely look and fix.

Thanks!
